### PR TITLE
Fixed markdown lints

### PR DESCRIPTION
**Pull request by BenMatase**
So that we no longer have to ignore the markdown lint errors

### CODE REVIEW

**Review by gregschrock — APPROVED** [review]
This is fine; it might make merges from remote a bit of a pain though.

**Comment by BenMatase** [comment]
> This is fine; it might make merges from remote a bit of a pain though.

Sure. I mean the other thing is that I could fix our files and then skip linting (assuming we can do that) for the common merge conflict files. Specifically `README.md` at the top level

**Comment by gregschrock** [comment]
That's not a bad idea. I don't have a strong preference either way.

**Comment by BenMatase** [comment]
Undid the testing changes. Lets move forward with what I have/had

**Review by gregschrock — APPROVED** [review]

**Pull request merged**
